export { default as SecBootCamp } from '../components/bootcamps/SecBootCamp'
export { default as DevBootCamp } from '../components/bootcamps/DevBootCamp'
export { default as MgtBootCamp } from '../components/bootcamps/MgtBootCamp'
export { default as About } from './about/About'
export { default as Home} from './home/Home'
export { default as Contact } from './contact/Contact'
export { default as NavBar } from './navbar/NavBar'
export { default as Blog } from './blog/Blog'
export { default as Footer } from './footer/Footer'